#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Build Claude Desktop-installable zips for every skill.

Claude Desktop accepts a .zip/.skill containing a SKILL.md with YAML
name + description. Each zip here contains the skill directory as its
top-level folder (e.g. wifi-qr/SKILL.md), which is what the desktop
uploader expects on unzip.

Codex-only artifacts (the per-skill agents/ dir) are excluded — they are
irrelevant to Claude Desktop and only add noise.

Also (re)generates desktop-install-ready/README.md with a table of every
skill: name, purpose, and a clickable download link.

Usage:
    python3 scripts/build_desktop_zips.py           # build all
    python3 scripts/build_desktop_zips.py wifi-qr    # build one

This is also called automatically by scripts/sync_codex_packaging.py.
"""

from __future__ import annotations

import re
import sys
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO / "skills"
OUT_DIR = REPO / "desktop-install-ready"
RAW_BASE = "https://github.com/carlkibler/agent-skills/raw/main/desktop-install-ready"

# Single source of truth for skill grouping — imported by sync_codex_packaging.py
# so the main README and the desktop README always agree on order and intros.
# Non-technical groups first, so a non-developer sees what's for them at the top.
GROUP_ORDER = ["For Anyone", "Product & Launch", "Dev Workflow", "Homelab & Personal Ops"]
GROUP_INTROS = {
    "For Anyone": "Broadly useful, no coding required — point them at a plan, your contacts, or a person and go.",
    "Product & Launch": "Stress-test a product before real users do: onboarding, trust, support load, launch readiness.",
    "Dev Workflow": "Tools for the day-to-day of writing, reviewing, and releasing code.",
    "Homelab & Personal Ops": "Machine, dotfile, and homelab housekeeping (Carl-specific, but adaptable).",
}

# Directories inside a skill that are Codex-specific and not needed by Desktop.
EXCLUDE_DIRS = {"agents"}
# File patterns to skip everywhere.
EXCLUDE_NAMES = {".DS_Store"}


def parse_frontmatter(text: str) -> dict[str, str]:
    match = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not match:
        return {}
    meta: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        meta[key.strip()] = value.strip().strip('"')
    return meta


def iter_skill_files(skill_dir: Path):
    for path in sorted(skill_dir.rglob("*")):
        if path.is_dir():
            continue
        rel = path.relative_to(skill_dir)
        if rel.parts and rel.parts[0] in EXCLUDE_DIRS:
            continue
        if path.name in EXCLUDE_NAMES:
            continue
        yield path, rel


# Fixed timestamp so identical content always produces byte-identical zips —
# otherwise the pre-commit sync hook rebuilds them every run and never settles.
FIXED_DATE = (1980, 1, 1, 0, 0, 0)


def build_zip(skill_dir: Path) -> Path | None:
    name = skill_dir.name
    if not (skill_dir / "SKILL.md").exists():
        return None
    OUT_DIR.mkdir(exist_ok=True)
    zip_path = OUT_DIR / f"{name}.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for path, rel in iter_skill_files(skill_dir):
            info = zipfile.ZipInfo(f"{name}/{rel.as_posix()}", date_time=FIXED_DATE)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            zf.writestr(info, path.read_bytes())
    return zip_path


def write_folder_readme(skills: list[dict[str, str]]) -> None:
    by_group: dict[str, list[dict[str, str]]] = {}
    for s in skills:
        by_group.setdefault(s["group"], []).append(s)
    ordered = [g for g in GROUP_ORDER if by_group.get(g)]
    ordered += sorted(g for g in by_group if g not in GROUP_ORDER)

    sections = []
    for group in ordered:
        rows = "\n".join(
            f"| **{s['name']}** | {s['summary']} | [Download]({RAW_BASE}/{s['name']}.zip) |"
            for s in sorted(by_group[group], key=lambda s: s["name"])
        )
        intro = GROUP_INTROS.get(group, "")
        head = f"### {group}\n\n" + (f"{intro}\n\n" if intro else "")
        sections.append(f"{head}| Skill | Purpose | Download |\n|-------|---------|----------|\n{rows}")
    skills_body = "\n\n".join(sections)

    body = f"""# Desktop-install-ready skills

Prebuilt `.zip` bundles of every skill, ready to upload to **Claude Desktop**.

Each zip unpacks to `<skill>/SKILL.md` (name + description in YAML
frontmatter), plus any `scripts/`, `references/`, and `assets/`. The
Codex-only `agents/` dir is excluded — Claude Desktop doesn't use it.

## Install

1. Click **Download** for the skill you want.
2. In Claude Desktop: Settings → Capabilities → Skills → **Upload skill**.
3. Select the `.zip`.

## Skills

{skills_body}

---

_Generated by `scripts/build_desktop_zips.py` (run automatically by
`scripts/sync_codex_packaging.py`). After editing a skill, rebuild with:_

```bash
python3 scripts/build_desktop_zips.py          # all skills
python3 scripts/build_desktop_zips.py wifi-qr  # one skill
```
"""
    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / "README.md").write_text(body)


def build(targets: list[str] | None = None, *, quiet: bool = False) -> list[dict[str, str]]:
    """Build zips and the folder README. Returns per-skill metadata."""
    if targets:
        skill_dirs = [SKILLS_DIR / t for t in targets]
    else:
        skill_dirs = [d for d in sorted(SKILLS_DIR.iterdir()) if d.is_dir()]

    # README always reflects every skill, not just the built subset.
    all_meta = []
    for d in sorted(SKILLS_DIR.iterdir()):
        if not (d.is_dir() and (d / "SKILL.md").exists()):
            continue
        fm = parse_frontmatter((d / "SKILL.md").read_text())
        all_meta.append(
            {
                "name": d.name,
                "summary": fm.get("summary", fm.get("description", d.name)),
                "group": fm.get("group", "Dev Workflow"),
            }
        )

    built = 0
    for skill_dir in skill_dirs:
        if not skill_dir.is_dir():
            if not quiet:
                print(f"  SKIP {skill_dir.name}: not a directory")
            continue
        result = build_zip(skill_dir)
        if result is None:
            if not quiet:
                print(f"  SKIP {skill_dir.name}: no SKILL.md")
            continue
        built += 1
        if not quiet:
            print(f"  OK   {result.relative_to(REPO)} ({result.stat().st_size / 1024:.1f} KB)")

    write_folder_readme(all_meta)
    if not quiet:
        print(f"\nBuilt {built} desktop-ready zip(s) in {OUT_DIR.relative_to(REPO)}/")
    return all_meta


if __name__ == "__main__":
    build(sys.argv[1:] or None)
